CK\BasicCmsBundle\Document\Page:
    uri_schema: /page/{title}
    token_providers:
        title: [content_method, { method: getTitle }]

CK\BasicCmsBundle\Document\Post:
    uri_schema: /post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate }]
        title: [content_method, { method: getTitle }]

CK\BasicCmsBundle\Document\Article:
    uri_schema: /article/{title}
    token_providers:
        title: [content_method, { method: getTitle }]