services:
    ck_basiccms.basic_cms.phpcr.initializer:
        class: Doctrine\Bundle\PHPCRBundle\Initializer\GenericInitializer
        arguments:
            - My custom initializer
            - ["/cms/pages", "/cms/posts", "/cms/routes"]
        tags:
            - { name: doctrine_phpcr.initializer }

    ck.basic_cms.admin.page:
        class: CK\BasicCmsBundle\Admin\PageAdmin
        arguments:
            - ''
            - CK\BasicCmsBundle\Document\Page
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: Page }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]

    ck.basic_cms.admin.post:
        class: CK\BasicCmsBundle\Admin\PostAdmin
        arguments:
            - ''
            - CK\BasicCmsBundle\Document\Post
            - 'SonataAdminBundle:CRUD'
        tags:
            - { name: sonata.admin, manager_type: doctrine_phpcr, group: 'Basic CMS', label: 'Blog Posts' }
        calls:
            - [setRouteBuilder, ['@sonata.admin.route.path_info_slashes']]